apiVersion: v1
kind: Service
metadata:
  name: private-checkout
  namespace: wasmcloud
  labels:
    app.kubernetes.io/managed-by: di-framework
    app.kubernetes.io/name: private-checkout
    di-framework.dev/application: "private-checkout"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: private-checkout
  namespace: wasmcloud
  labels:
    app.kubernetes.io/managed-by: di-framework
    app.kubernetes.io/name: private-checkout
    di-framework.dev/application: "private-checkout"
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      kubernetes:
        service:
          name: private-checkout
      components:
        - name: private-checkout
          image: "registry.invalid/verification:probe"
      hostInterfaces:
        - namespace: wasi
          package: http
          version: "0.3.0"
          interfaces:
            - handler
          config:
            "host": "private-checkout"
